receivers:
  prefix_compressed_receiver: 
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [prefix_compressed_receiver]
      processors: [batch]
      exporters: [debug, otlp]
  telemetry:
    logs:
      level: debug