version: "3.9"
services:
  social-graph-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    depends_on:
      otelcol:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config

  social-graph-mongodb:
    image: mongo:4.4.6
    hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    restart: always

  social-graph-redis:
    image: redis
    hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    restart: always

  home-timeline-redis:
    image: redis
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    restart: always

  compose-post-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config

  post-storage-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: post-storage-service
    ports:
      - 10002:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config

  post-storage-memcached:
    image: memcached
    hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    restart: always

  post-storage-mongodb:
    image: mongo:4.4.6
    hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    restart: always

  user-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint: UserTimelineService
    volumes:
      - ./user-timeline-service/config:/social-network-microservices/config

  user-timeline-redis:
    image: redis
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    restart: always

  user-timeline-mongodb:
    image: mongo:4.4.6
    hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    restart: always

  url-shorten-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      otelcol:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    volumes:
      - ./config:/social-network-microservices/config

  url-shorten-memcached:
    image: memcached
    hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    restart: always

  url-shorten-mongodb:
    image: mongo:4.4.6
    hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    restart: always

  user-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-service
    #    ports:
    #      - 10005:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config

  user-memcached:
    image: memcached
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    restart: always

  user-mongodb:
    image: mongo:4.4.6
    hostname: user-mongodb
    # ports:
    #   - 27023:27017
    restart: always

  media-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: media-service
    #    ports:
    #      - 10006:9090
    depends_on:
      otelcol:
        condition: service_started
      media-mongodb:
        condition: service_started
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config

  media-memcached:
    image: memcached
    hostname: media-memcached
    #    ports:
    #      - 11215:11211
    restart: always

  media-mongodb:
    image: mongo:4.4.6
    hostname: media-mongodb
    #    ports:
    #      - 27024:27017
    restart: always

  text-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: text-service
    #    ports:
    #      - 10007:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config

  unique-id-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    restart: always
    depends_on:
      otelcol:
        condition: service_started
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config

  user-mention-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      otelcol:
        condition: service_started
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config

  home-timeline-service:
    image: deathstarbench/social-network-microservices:latest
    hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      otelcol:
        condition: service_started
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      userserviceagent:
        condition: service_started
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift

  media-frontend:
    image: yg397/media-frontend:xenial
    hostname: media-frontend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      otelcol:
        condition: service_started
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - "4317"
      - 16686:16686
      #      - 14268:14268
      #      - 9411:9411
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otelcol
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./config/otelcol-config.yml:/etc/otelcol-config.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "6831"          # jaeger-receiver over thrift receiver
      - "55679:55679"
      - "4317"
    depends_on:
      - compressoragent

  userserviceagent:
    image: angrychow1/selfmade_otel:latest
    container_name: userserviceagent
    restart: unless-stopped
    volumes:
      - ./config/user-service-agent-config.yml:/otel/user-service-agent-config.yml
    ports:
      - "4317"
      - "4318"
      - "8888"
      - "6831"
      - "55678"
      - "55679"
    depends_on:
        - compressorgateway
    command: ["--config", "user-service-agent-config.yml"]
  
  compressoragent:
    image: angrychow1/selfmade_otel:latest
    container_name: compressoragent
    restart: unless-stopped
    volumes:
      - ./config/agent-config.yml:/otel/agent-config.yml
    ports:
      - "4317"
      - "4318"
      - "8888"
      - "55678"
      - "55679"
    depends_on:
        - compressorgateway
    command: ["--config", "agent-config.yml"]

  compressorgateway:
    image: angrychow1/selfmade_otel:latest
    container_name: compressorgateway
    restart: unless-stopped
    volumes:
      - ./config/gateway-config.yml:/otel/gateway-config.yml
    command: ["--config", "gateway-config.yml"]
    ports:
      - "4317"
      - "4318"
      - "8888"
      - "55678"
      - "55679"
    depends_on:
      - jaeger